### ISSUE TITLE
Sly undefined method error `color`

### ISSUE THREAD

**Issue by nanno77** [Haar/Sprintly-Terminal#8] opened 2014-07-21 23:27 UTC
I am getting the following error when I try to run any sly command
error: undefined method `color' for "#125 - ":String

Ruby 2.1.1 is my current version of ruby. 

Thanks

**Comment by Haar** [comment] 2014-07-22 13:44
Hey, thanks for the report.

My current client project has been on Pivotal Tracker so I've not used sly recently, I'll have a look at what's causing this issue ASAP.

**Comment by Haar** [comment] 2014-07-22 18:40
The issue was caused by not specifying a version of Rainbow (v 1.x was fine, 2.x not) - should be fixed by https://github.com/Haar/Sprintly-Terminal/pull/9. 

Just noticed another issue that I'll try and get fixed, and will release to RubyGems after addressing that.

**Closed as completed** 2014-07-23 08:43 UTC
